#!/usr/bin/env bash
# shellcheck disable=SC2034
set -euo pipefail

# Conky Cybersecurity Monitor – Full App (Hardened & ShellCheck Compliant)
#
# Este script instala, configura y gestiona Conky junto con herramientas de seguridad
# (como RKHunter) utilizando una interfaz gráfica basada en dialog.
# También crea un lanzador de escritorio para iniciar la aplicación sin una terminal.
#
# Autor: jose-litium 2025
# GitHub: https://github.com/jose-litium
# LinkedIn: https://www.linkedin.com/in/josemmanueldiaz/
# Fecha: 2025-02-17 (Modificado: 2025-05-07)
# Hardening: 2026-06-01

########################################
# Global Configuration
########################################

readonly INSTALL_DIR="$HOME/.local/conky_app"
mkdir -p "$INSTALL_DIR"
chmod 0700 "$INSTALL_DIR"
readonly LOGFILE="$INSTALL_DIR/conky_gui_$$_.log"
readonly SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_PATH="$(readlink -f "$0")"

# Track if apt update has been executed
APT_HAS_UPDATED=""

# Define colors for terminal output (for logs)
readonly BLUE='\033[1;34m'
readonly CYAN='\033[1;36m'
readonly GREEN='\033[1;32m'
readonly MAGENTA='\033[1;35m'
readonly YELLOW='\033[1;33m'
readonly WHITE='\033[1;37m'
readonly RED='\033[1;31m'
readonly NC='\033[0m'

########################################
# Cleanup & Signal Handling
########################################

cleanup() {
    local exit_code=$?
    log "Script exiting with code: $exit_code"
    # Secure removal of sensitive temp files
    rm -f "$INSTALL_DIR/rkhunter_result."* "$INSTALL_DIR/rkhunter_warnings"*.txt "$INSTALL_DIR/cpu_temp.txt" 2>/dev/null || true
    exit "$exit_code"
}

trap cleanup EXIT INT TERM

########################################
# Utility Functions
########################################

# Check if a command is installed
is_command_installed() {
    command -v "$1" &>/dev/null
}

# Confirmation dialog
dconfirm() {
    dialog --clear --yesno "$1" 7 60
    return $?
}

# Message dialog
dmsg() {
    dialog --clear --msgbox "$1" 10 60
}

# Menu dialog (returns the chosen option)
dmenu() {
    local title="$1"
    shift
    local -a options=("$@")
    local choice
    choice=$(dialog --clear --backtitle "Conky Cybersecurity Monitor" \
        --title "$title" \
        --menu "Choose an option:" 24 70 17 "${options[@]}" 2>&1 >/dev/tty) || return 1
    echo "$choice"
}

########################################
# Logging Functions
########################################

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $*" >> "$LOGFILE"
}

clear_log_file() {
    : > "$LOGFILE"
}

run_cmd() {
    log "Running: $*"
    "$@" >> "$LOGFILE" 2>&1
}

########################################
# Sudoers Configuration (Hardened)
########################################

setup_sudoers() {
    # Validate and escape USER to prevent Command Injection / Privilege Escalation
    if [[ ! "$USER" =~ ^[a-zA-Z0-9_.-]+$ ]]; then
        log "ERROR: Invalid USER variable format."
        return 1
    fi
    local safe_user
    safe_user="$(printf '%q' "$USER")"

    local sudoers_file="/etc/sudoers.d/conky-monitor"
    local wrapper_script="/usr/local/bin/conky-rkhunter-wrapper.sh"

    # Create wrapper script for rkhunter
    sudo tee "$wrapper_script" > /dev/null <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

# Secure wrapper for rkhunter to prevent complex argument matching in sudoers
case "${1:-}" in
    --update)
        exec /usr/bin/rkhunter --update
        ;;
    --propupd)
        exec /usr/bin/rkhunter --propupd
        ;;
    --check)
        if [[ "${2:-}" == "--sk" && -z "${3:-}" ]]; then
            exec /usr/bin/rkhunter --check --sk
        else
            echo "Invalid arguments" >&2
            exit 1
        fi
        ;;
    *)
        echo "Invalid arguments" >&2
        exit 1
        ;;
esac
EOF
    sudo chmod 755 "$wrapper_script"
    
    # Create secure sudoers entry with minimal required permissions
    sudo tee "$sudoers_file" > /dev/null <<EOF
# Conky Cybersecurity Monitor - Minimal sudo permissions
# Generated by conky-cybersecurity-monitor.sh

# Allow user to run the specific wrapper script without password
${safe_user} ALL=(ALL) NOPASSWD: /usr/local/bin/conky-rkhunter-wrapper.sh
EOF
    
    # Set secure permissions
    sudo chmod 0440 "$sudoers_file"
    
    # Validate sudoers syntax before applying
    if sudo visudo -c -f "$sudoers_file" &>/dev/null; then
        log "Sudoers configuration validated and applied for user $USER."
    else
        log "ERROR: Sudoers syntax validation failed. Rolling back."
        sudo rm -f "$sudoers_file"
        return 1
    fi
}

########################################
# Internal Checks
########################################

check_user_systemd() {
    if ! systemctl --user 2>/dev/null; then
        dmsg "User-level systemd is not available.\nPlease use a version of Ubuntu/Debian with a desktop environment (18.04+)."
        log "ERROR: User systemd not available"
        exit 1
    fi
}

check_install() {
    local pkgs=("$@")
    local missing_pkgs=()

    for pkg in "${pkgs[@]}"; do
        if dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q " ok installed"; then
            log "$pkg is already installed."
        else
            log "$pkg is not installed."
            missing_pkgs+=("$pkg")
        fi
    done

    if [[ ${#missing_pkgs[@]} -eq 0 ]]; then
        return 0
    fi

    local pkg_list="${missing_pkgs[*]}"
    if dconfirm "Do you want to install the following missing packages?\n$pkg_list"; then
        if [[ -z "$APT_HAS_UPDATED" ]]; then
            sudo apt update
            APT_HAS_UPDATED=1
        fi
        if sudo apt install -y "${missing_pkgs[@]}"; then
            log "Successfully installed packages: $pkg_list"
            return 0
        else
            log "ERROR: Failed to install packages: $pkg_list"
            dmsg "Failed to install packages. This may affect functionality."
            return 1
        fi
    else
        dmsg "Skipped installing packages: $pkg_list. This may affect functionality."
        return 1
    fi
}

configure_sensors() {
    echo -e "${BLUE}Configuring hardware sensors (lm-sensors)...${NC}"
    if command -v sensors &>/dev/null; then
        if dconfirm "Do you want to run sensors-detect to automatically configure your sensors?"; then
            echo -e "${BLUE}Running sensors-detect (auto-accept defaults)...${NC}"
            # Use --auto to avoid interactive prompts, redirect output to log
            if yes | sudo sensors-detect &>> "$LOGFILE"; then
                # Load detected modules
                sudo modprobe -a coretemp it87 2>/dev/null || true
                dmsg "Sensors configuration completed."
                log "Sensors configured successfully."
            else
                log "WARNING: sensors-detect completed with warnings"
                dmsg "Sensors configuration completed with warnings. Check logs."
            fi
        else
            dmsg "Skipped configuration with sensors-detect."
            log "Sensors-detect skipped by user."
        fi
    else
        dmsg "lm-sensors is not installed. Skipping sensor configuration."
        log "lm-sensors not available, skipping sensor config."
    fi
}

create_rkhunter_scan_script() {
    local script_path="$INSTALL_DIR/rkhunter_scan.sh"
    cat <<'EOF' > "$script_path"
#!/usr/bin/env bash
set -euo pipefail

# Secure RKHunter scan script for Conky Monitor
# Outputs warnings to a temp file for Conky to display

readonly INSTALL_DIR="$HOME/.local/conky_app"
readonly WARN_FILE="/var/log/rkhunter_warnings.txt"
readonly RESULT_FILE="$(mktemp "$INSTALL_DIR/rkhunter_result.XXXXXX")"

cleanup() {
    rm -f "$RESULT_FILE" 2>/dev/null || true
}
trap cleanup EXIT

# Update RKHunter databases (silent)
sudo /usr/local/bin/conky-rkhunter-wrapper.sh --update >/dev/null 2>&1 || true
sudo /usr/local/bin/conky-rkhunter-wrapper.sh --propupd >/dev/null 2>&1 || true

# Run check and capture output
if sudo /usr/local/bin/conky-rkhunter-wrapper.sh --check --sk > "$RESULT_FILE" 2>/dev/null; then
    # Extract only warning lines for Conky display
    grep -iE "(warning|alert|suspect)" "$RESULT_FILE" > "$WARN_FILE" 2>/dev/null || true
    
    # Create comparison file for change detection
    if [[ -f "/var/log/rkhunter_warnings_prev.txt" ]]; then
        if ! cmp -s "$WARN_FILE" "/var/log/rkhunter_warnings_prev.txt"; then
            cp "$WARN_FILE" "/var/log/rkhunter_warnings_prev.txt"
            echo "CHANGED" > "/var/log/rkhunter_status.txt"
        else
            echo "UNCHANGED" > "/var/log/rkhunter_status.txt"
        fi
    else
        cp "$WARN_FILE" "/var/log/rkhunter_warnings_prev.txt" 2>/dev/null || true
        echo "INITIAL" > "/var/log/rkhunter_status.txt"
    fi
fi

# Ensure file exists even if empty (for Conky to read)
touch "$WARN_FILE"
EOF
    chmod 700 "$script_path"
    log "RKHunter scan script created at $script_path with secure permissions."
}

create_temp_monitor_script() {
    local script_path="$INSTALL_DIR/temp_monitor.sh"
    cat <<'EOF' > "$script_path"
#!/usr/bin/env bash
set -euo pipefail

# CPU Temperature Monitor for Conky
# Writes safe, sanitized output to temp file

readonly INSTALL_DIR="$HOME/.local/conky_app"
readonly TEMP_FILE="$INSTALL_DIR/cpu_temp.txt"
readonly MAX_SAFE_TEMP=90

cleanup() {
    rm -f "$TEMP_FILE" 2>/dev/null || true
}
trap cleanup EXIT

while true; do
    # Safely extract temperature value
    local temp_raw
    temp_raw="$(sensors 2>/dev/null | grep -Eo 'Package id 0:.*\+[0-9.]+' | head -n1 | grep -Eo '\+[0-9.]+' | tr -d '+' || echo "")"
    
    if [[ -n "$temp_raw" ]]; then
        # Validate it's a number
        if [[ "$temp_raw" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
            local temp_val
            temp_val="$(printf "%.1f" "$temp_raw")"
            # Cap at MAX_SAFE_TEMP to avoid display issues
            local tmp_file
            tmp_file="$(mktemp "$INSTALL_DIR/cpu_temp.XXXXXX")"
            if awk "BEGIN {exit !($temp_val > $MAX_SAFE_TEMP)}"; then
                echo ">${MAX_SAFE_TEMP}°C" > "$tmp_file"
            else
                echo "${temp_val}°C" > "$tmp_file"
            fi
            mv "$tmp_file" "$TEMP_FILE"
        else
            local tmp_file
            tmp_file="$(mktemp "$INSTALL_DIR/cpu_temp.XXXXXX")"
            echo "N/A" > "$tmp_file"
            mv "$tmp_file" "$TEMP_FILE"
        fi
    else
        local tmp_file
        tmp_file="$(mktemp "$INSTALL_DIR/cpu_temp.XXXXXX")"
        echo "N/A" > "$tmp_file"
        mv "$tmp_file" "$TEMP_FILE"
    fi
    sleep 10
done
EOF
    chmod 700 "$script_path"
    log "Temperature monitor script created at $script_path with secure permissions."
}

install_temp_monitor_service() {
    mkdir -p ~/.config/systemd/user
    cat <<EOL > ~/.config/systemd/user/temp_monitor.service
[Unit]
Description=CPU Temperature Monitor for Conky Cybersecurity Dashboard
After=default.target
Wants=default.target

[Service]
Type=simple
ExecStart=/usr/bin/env bash "$INSTALL_DIR/temp_monitor.sh"
Restart=on-failure
RestartSec=5
PrivateTmp=true
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=/tmp

[Install]
WantedBy=default.target
EOL

    systemctl --user daemon-reload
    systemctl --user enable --now temp_monitor.service 2>/dev/null || {
        log "WARNING: Could not enable temp_monitor.service (user systemd may not be running)"
        return 1
    }
    log "Temperature monitor service installed and started."
}

install_rkhunter_service() {
    echo -e "${BLUE}Installing automatic RKHunter scan service...${NC}"
    
    # Validate and escape USER to prevent Command Injection / Privilege Escalation
    if [[ ! "$USER" =~ ^[a-zA-Z0-9_.-]+$ ]]; then
        log "ERROR: Invalid USER variable format."
        return 1
    fi
    local safe_user
    safe_user="$(printf '%q' "$USER")"

    # System-level service for RKHunter (requires sudo)
    sudo tee /etc/systemd/system/rkhunter-auto.service > /dev/null <<'EOL'
[Unit]
Description=RKHunter Automatic Security Scan for Conky Monitor
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/rkhunter-auto-scan.sh
RemainAfterExit=yes
PrivateTmp=true
ProtectSystem=strict
ReadWritePaths=/var/log

[Install]
WantedBy=multi-user.target
EOL

    # Create the actual scan script with proper permissions
    sudo mkdir -p /usr/local/bin
    sudo tee /usr/local/bin/rkhunter-auto-scan.sh > /dev/null <<EOL
#!/usr/bin/env bash
set -euo pipefail
# Automated RKHunter scan wrapper for systemd

readonly WARN_FILE="/var/log/rkhunter_warnings.txt"
readonly RESULT_FILE="\$(mktemp)"
readonly CONKY_USER="${safe_user}"

cleanup() { rm -f "\$RESULT_FILE" 2>/dev/null || true; }
trap cleanup EXIT

/usr/bin/rkhunter --update >/dev/null 2>&1 || true
/usr/bin/rkhunter --propupd >/dev/null 2>&1 || true
/usr/bin/rkhunter --check --sk > "\$RESULT_FILE" 2>/dev/null || true

# Extract warnings for Conky
grep -iE "(warning|alert|suspect)" "\$RESULT_FILE" > "\$WARN_FILE" 2>/dev/null || touch "\$WARN_FILE"
chown "\${CONKY_USER}:\${CONKY_USER}" "\$WARN_FILE" 2>/dev/null || true
chmod 644 "\$WARN_FILE" 2>/dev/null || true
exit 0
EOL
    sudo chmod 750 /usr/local/bin/rkhunter-auto-scan.sh

    # Timer unit for periodic execution
    sudo tee /etc/systemd/system/rkhunter-auto.timer > /dev/null <<'EOL'
[Unit]
Description=Timer for RKHunter automatic security scans
Requires=rkhunter-auto.service

[Timer]
OnBootSec=10min
OnUnitActiveSec=6h
RandomizedDelaySec=30min
Persistent=true

[Install]
WantedBy=timers.target
EOL

    sudo systemctl daemon-reload
    sudo systemctl enable --now rkhunter-auto.timer 2>/dev/null || {
        log "WARNING: Could not enable rkhunter-auto.timer"
        return 1
    }
    log "RKHunter service and timer installed with hardened configuration."
}

remove_rkhunter_service() {
    echo -e "${RED}Removing automatic RKHunter scan service and timer...${NC}"
    
    # Stop and disable timer first
    sudo systemctl disable --now rkhunter-auto.timer 2>/dev/null || true
    sudo rm -f /etc/systemd/system/rkhunter-auto.timer
    
    # Stop and disable service
    sudo systemctl disable --now rkhunter-auto.service 2>/dev/null || true
    sudo rm -f /etc/systemd/system/rkhunter-auto.service
    
    # Remove helper script
    sudo rm -f /usr/local/bin/rkhunter-auto-scan.sh
    
    sudo systemctl daemon-reload
    log "RKHunter service, timer, and helper script removed."
}

########################################
# Functions: Delete Logs and Temporary Files
########################################

delete_temporaries() {
    # Resolved Git conflict: Keep comprehensive temp file cleanup
    local -a temp_files=(
        "$INSTALL_DIR/rkhunter_result.txt"
        "/var/log/rkhunter_warnings.txt"
        "/var/log/rkhunter_warnings_prev.txt"
        "/var/log/rkhunter_status.txt"
        "$INSTALL_DIR/cpu_temp.txt"
        "$INSTALL_DIR/rkhunter_result."*
        "$INSTALL_DIR/rkhunter_warnings_"*".txt"
    )
    
    for file in "${temp_files[@]}"; do
        rm -f "$file" 2>/dev/null || true
    done
    
    dmsg "Temporary files deleted securely."
    log "Temporary files cleaned up."
}

clear_logs() {
    clear_log_file
    dmsg "Log file cleared."
    log "Log file truncated."
}

view_logs() {
    if [[ -f "$LOGFILE" ]]; then
        dialog --textbox "$LOGFILE" 20 70
    else
        dmsg "Log file not found at $LOGFILE"
        log "WARNING: Attempted to view non-existent log file"
    fi
}

view_rkhunter_warnings() {
    local warn_log="/var/log/rkhunter_warnings.txt"

    local target_log="/var/log/rkhunter_warnings.txt"
    if false; then
        target_log="$target_log"
    fi
    if [[ -f "$target_log" && -s "$target_log" ]]; then
        dialog --textbox "$target_log" 20 70
    else
        dmsg "No RKHunter warnings found or file is empty."
        log "RKHunter warnings file empty or missing."
    fi
}

########################################
# Function: Install Pentesting Tools
########################################

install_pentest_tools() {
    if dconfirm "Install pentesting tools? (Already-installed tools will be skipped)"; then
        local -a tools=("nmap" "sqlmap" "aircrack-ng" "hydra" "john" "metasploit-framework" "wireshark")
        local installed=0 failed=0
        
        check_install "${tools[@]}"

        for tool in "${tools[@]}"; do
            if dpkg-query -W -f='${Status}' "$tool" 2>/dev/null | grep -q " ok installed"; then
                ((installed++)) || true
            else
                ((failed++)) || true
            fi
        done
        
        dmsg "Pentesting tools installation complete.\nInstalled: $installed | Failed/Skipped: $failed"
        log "Pentesting tools batch complete: $installed installed, $failed failed/skipped"
    else
        dmsg "Pentesting tools installation canceled by user."
        log "Pentesting tools installation canceled."
    fi
}

########################################
# Function: Clean /var/log
########################################

clean_var_log() {
    if dconfirm "Clean /var/log? This will vacuum journal logs to 1 day and truncate log files."; then
        # Safe log cleaning with error handling
        if sudo journalctl --vacuum-time=1d 2>/dev/null; then
            log "Journal vacuumed to 1 day"
        fi
        
        # Only truncate files that are safe to truncate (avoid critical system logs)
        local -a safe_logs=(
            "/var/log/apt/history.log"
            "/var/log/apt/term.log"
            "/var/log/bootstrap.log"
            "/var/log/dpkg.log"
        )
        
        for logfile in "${safe_logs[@]}"; do
            if [[ -f "$logfile" && -w "$logfile" ]]; then
                sudo truncate -s 0 "$logfile" 2>/dev/null || true
            fi
        done
        
        dmsg "/var/log system logs cleaned safely."
        log "/var/log cleaning completed."
    else
        dmsg "Cleaning /var/log canceled by user."
        log "/var/log cleaning canceled."
    fi
}

########################################
# Function: Create Desktop Launcher
########################################

create_launcher() {
    local desktop_file="$HOME/.local/share/applications/conky-cybersecurity-monitor.desktop"
    mkdir -p "$(dirname "$desktop_file")"
    
    cat > "$desktop_file" <<EOF
[Desktop Entry]
Name=Conky Cybersecurity Monitor
Comment=Manage Conky with integrated security monitoring (RKHunter, sensors, network)
Exec=$SCRIPT_PATH
Icon=utilities-system-monitor
Terminal=false
Type=Application
Categories=Utility;Security;Monitor;
Keywords=conky;security;monitoring;rkhunter;system;
StartupNotify=true
EOF
    
    chmod 644 "$desktop_file"
    
    # Update desktop database if available
    if command -v update-desktop-database &>/dev/null; then
        update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true
    fi
    
    dmsg "Desktop launcher created at $desktop_file"
    log "Desktop launcher created: $desktop_file"
}

########################################
# Dependency Check Function (Hardened)
########################################

check_dependencies() {
    declare -A required_commands=(
        ["dialog"]="dialog"
        ["conky"]="conky-all"
        ["curl"]="curl"
        ["netstat"]="net-tools"
        ["lsof"]="lsof"
        ["xdg-open"]="xdg-utils"
        ["rkhunter"]="rkhunter"
        ["sensors"]="lm-sensors"
        ["nmap"]="nmap"
        ["upower"]="upower"
    )
    
    local -a missing_dependencies=()
    
    for cmd in "${!required_commands[@]}"; do
        if ! is_command_installed "$cmd"; then
            missing_dependencies+=("${required_commands[$cmd]}")
        fi
    done

    if [[ ${#missing_dependencies[@]} -gt 0 ]]; then
        echo -e "${RED}Faltan las siguientes dependencias:${NC}" >&2
        for dep in "${missing_dependencies[@]}"; do
            echo "- $dep" >&2
        done
        echo -e "${YELLOW}Por favor, instala las dependencias que faltan usando el gestor de paquetes de tu sistema.${NC}" >&2

        if is_command_installed "apt"; then
            echo "Ejemplo para Debian/Ubuntu: sudo apt install ${missing_dependencies[*]}" >&2
        elif is_command_installed "dnf"; then
            echo "Ejemplo para Fedora: sudo dnf install ${missing_dependencies[*]}" >&2
        elif is_command_installed "yum"; then
            echo "Ejemplo para RHEL/CentOS: sudo yum install ${missing_dependencies[*]}" >&2
        elif is_command_installed "pacman"; then
            echo "Ejemplo para Arch: sudo pacman -S ${missing_dependencies[*]}" >&2
        else
            echo "No se detectó un gestor de paquetes común. Instala manualmente las dependencias." >&2
        fi
        
        log "ERROR: Missing dependencies: ${missing_dependencies[*]}"
        exit 1
    fi
    log "All dependencies satisfied."
}

########################################
# Main Action Functions
########################################

install_conky() {
    if ! dconfirm "Proceed with Conky installation and configuration?"; then
        dmsg "Installation canceled by user."
        log "Installation canceled by user"
        return 1
    fi
    
    clear_log_file
    log "Starting Conky installation and configuration..."
    check_user_systemd
    
    echo -e "${BLUE}Updating package lists...${NC}"
    if [[ -z "$APT_HAS_UPDATED" ]]; then
        sudo apt update
        APT_HAS_UPDATED=1
    fi

    local -a apps=("conky-all" "curl" "net-tools" "lsof" "xdg-utils" "rkhunter" "lm-sensors" "nmap" "upower")
    local installed_count=0
    
    check_install "${apps[@]}"

    for pkg in "${apps[@]}"; do
        if dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q " ok installed"; then
            ((installed_count++)) || true
        fi
    done
    
    log "Installed $installed_count of ${#apps[@]} required packages"

    configure_sensors
    create_rkhunter_scan_script

    echo -e "${BLUE}Adjusting permissions for RKHunter logs...${NC}"
    if [[ -f /var/log/rkhunter.log ]]; then
        sudo chmod 644 /var/log/rkhunter.log 2>/dev/null || true
    fi
    sudo touch /var/log/rkhunter_warnings.txt /var/log/rkhunter_warnings_prev.txt /var/log/rkhunter_status.txt 2>/dev/null || true
    sudo chown "${USER}:${USER}" /var/log/rkhunter_warnings.txt /var/log/rkhunter_warnings_prev.txt /var/log/rkhunter_status.txt 2>/dev/null || true
    sudo chmod 644 /var/log/rkhunter_warnings.txt /var/log/rkhunter_warnings_prev.txt /var/log/rkhunter_status.txt 2>/dev/null || true

    echo -e "${BLUE}Configuring sudoers for Conky commands...${NC}"
    if ! setup_sudoers; then
        dmsg "WARNING: Sudoers configuration failed. Some features may require manual password entry."
        log "WARNING: Sudoers setup failed"
    fi

    mkdir -p ~/.config/conky
    local username="$USER"
    local home_dir="$HOME"
    
    echo -e "${BLUE}Creating hardened Conky configuration...${NC}"
    # Use double-quoted heredoc with proper variable escaping
    cat > ~/.config/conky/conky.conf <<EOL
conky.config = {
    alignment = 'top_right',
    background = false,
    double_buffer = true,
    update_interval = 1,
    own_window = true,
    own_window_type = 'desktop',
    own_window_argb_visual = true,
    own_window_argb_value = 140,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    gap_x = 15,
    gap_y = 50,
    minimum_width = 300,
    minimum_height = 750,
    draw_shades = false,
    draw_borders = false,
    use_xft = true,
    default_color = 'white',
    default_outline_color = 'blue',
    override_utf8_locale = true,
};

conky.text = [[
\${exec $home_dir/.local/conky_app/rkhunter_scan.sh > /dev/null 2>&1}
\${color yellow}\${time %H:%M:%S}      Vietnam (GMT+7)
\${color cyan}\${execi 10 TZ='Europe/Madrid' date '+%H:%M:%S'}      Madrid (GMT+1)
\${color green}\${execi 10 TZ='Australia/Sydney' date '+%H:%M:%S'}      Sydney (GMT+10)
\${color magenta}\${execi 10 TZ='America/New_York' date '+%H:%M:%S'}      New York (GMT-5)

\${color magenta}------ Hardware Indicators ------
\${color white}CPU: \${if_match \${cpu cpu0} > 80}\${color red}\${cpu cpu0}%\${else}\${color green}\${cpu cpu0}%\${endif} \${cpubar cpu0 10,}
\${color white}RAM: \${if_match \${memperc} > 40}\${color red}\${memperc}%\${else}\${color green}\${memperc}%\${endif} \${membar 10}
\${color white}Main HDD: \${if_match \${fs_used_perc /} > 60}\${color red}\${fs_used_perc /}%\${else}\${color green}\${fs_used_perc /}%\${endif} \${fs_bar /}
\${color white}CPU Temp: \${color red}\${execi 10 cat $home_dir/.local/conky_app/cpu_temp.txt 2>/dev/null | head -n1 || echo "N/A"}
\${color white}Uptime: \${color green}\${uptime}

\${color magenta}------ Network Information ------
\${color white}Local IP: \${color cyan}\${execi 10 hostname -I 2>/dev/null | cut -d' ' -f1 || echo "N/A"}
\${color white}Public IP: \${color cyan}\${execi 600 curl -s --max-time 10 ifconfig.me 2>/dev/null || echo "N/A"}
\${color white}VPN: \${execi 30 bash -c 'if ip link show 2>/dev/null | grep -Eiq "^(tun|tap|ppp)"; then echo "\${color yellow}Active\${color white}"; else echo "\${color yellow}Inactive\${color white}"; fi'}
\${color white}SSH Status: \${color yellow}\${execi 30 systemctl is-active ssh 2>/dev/null || echo "inactive"}
\${color white}Established Connections: \${color red}\${execi 10 netstat -an 2>/dev/null | grep -c ESTABLISHED || echo "0"}
\${color white}Open Ports: \${color red}\${execi 10 netstat -tuln 2>/dev/null | grep -c LISTEN || echo "0"}

\${color magenta}------ Connected Users ------
\${color white}Users: \${color cyan}\${execi 30 who 2>/dev/null | awk '{print \$1}' | sort -u | xargs || echo "None"}

\${color magenta}------ Security Events ------
\${color white}Recent Events: \${color red}\${execi 30 journalctl -n 5 -p 3 -u ssh.service --no-pager 2>/dev/null | tail -n 5 || echo "No recent events"}

\${color magenta}------ Rootkit Alerts ------
\${color white}Alerts: \${execi 600 bash -c 'if [[ -f /var/log/rkhunter_status.txt ]]; then status=\$(cat /var/log/rkhunter_status.txt); if [[ "\$status" == "CHANGED" ]]; then echo "New alerts - check /var/log/rkhunter_warnings.txt"; elif [[ -s /var/log/rkhunter_warnings.txt ]] ; then echo "Alerts present"; else echo "No alerts"; fi; else echo "Initializing..."; fi'}

\${color magenta}------ Top 5 Processes ------
\${color white}\${execi 5 ps -eo pid,comm,%cpu --sort=-%cpu 2>/dev/null | head -n 6 | tail -n 5}
]];
EOL

    # Create user systemd service for Conky
    mkdir -p ~/.config/systemd/user
    cat > ~/.config/systemd/user/conky.service <<EOL
[Unit]
Description=Conky Cybersecurity Monitor (User Level)
After=default.target graphical-session.target
Wants=default.target

[Service]
Type=simple
ExecStart=/usr/bin/conky -b -c "$home_dir/.config/conky/conky.conf"
Restart=on-failure
RestartSec=10
PrivateTmp=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=$home_dir/.config/conky /tmp
NoNewPrivileges=true

[Install]
WantedBy=default.target
EOL

    systemctl --user daemon-reload
    systemctl --user enable --now conky.service 2>/dev/null || {
        log "WARNING: Could not start conky.service (user systemd may not be active)"
        dmsg "Conky installed. Start manually with: systemctl --user start conky.service"
    }

    dmsg "Conky installation completed."
    log "Conky installed and configured."
    
    # Install supporting services
    create_temp_monitor_script
    install_temp_monitor_service
    install_rkhunter_service
}

uninstall_conky() {
    if ! dconfirm "Are you sure you want to completely remove Conky and all its components?"; then
        dmsg "Uninstallation canceled by user."
        return 1
    fi
    
    echo -e "${RED}Stopping Conky and related services...${NC}"
    
    # Stop user services
    systemctl --user stop conky.service 2>/dev/null || true
    systemctl --user disable conky.service 2>/dev/null || true
    rm -f ~/.config/systemd/user/conky.service
    
    systemctl --user stop temp_monitor.service 2>/dev/null || true
    systemctl --user disable temp_monitor.service 2>/dev/null || true
    rm -f ~/.config/systemd/user/temp_monitor.service
    
    systemctl --user daemon-reload 2>/dev/null || true
    
    # Kill any remaining conky processes
    pkill -f "conky.*conky.conf" 2>/dev/null || true
    sleep 2
    
    echo -e "${RED}Removing configuration files...${NC}"
    rm -rf ~/.config/conky
    rm -rf "$INSTALL_DIR"
    
    echo -e "${GREEN}Removing packages...${NC}"
    sudo apt remove --purge -y conky conky-all 2>/dev/null || true
    sudo apt autoremove -y 2>/dev/null || true
    
    # Remove sudoers entry and wrapper script
    sudo rm -f /etc/sudoers.d/conky-monitor 2>/dev/null || true
    sudo rm -f /usr/local/bin/conky-rkhunter-wrapper.sh 2>/dev/null || true
    
    # Remove system-level RKHunter services
    remove_rkhunter_service 2>/dev/null || true
    
    dmsg "Conky uninstallation completed. Temporary files can be cleaned separately."
    log "Conky completely uninstalled."
}

start_conky() {
    echo -e "${GREEN}Starting Conky service...${NC}"
    if [[ -f ~/.config/systemd/user/conky.service ]]; then
        if systemctl --user start conky.service 2>/dev/null; then
            dmsg "Conky service started successfully."
            log "Conky service started"
        else
            dmsg "Failed to start Conky service. Check: systemctl --user status conky.service"
            log "ERROR: Failed to start conky.service"
            return 1
        fi
    else
        dmsg "Conky service not found. Please install Conky first."
        log "ERROR: conky.service not found"
        return 1
    fi
}

stop_conky() {
    echo -e "${GREEN}Stopping Conky service...${NC}"
    if [[ -f ~/.config/systemd/user/conky.service ]]; then
        if systemctl --user stop conky.service 2>/dev/null; then
            dmsg "Conky service stopped."
            log "Conky service stopped"
        else
            dmsg "Failed to stop Conky service."
            log "WARNING: Could not stop conky.service"
            return 1
        fi
    else
        dmsg "Conky service not found. Please install Conky first."
        return 1
    fi
}

restart_conky() {
    echo -e "${GREEN}Restarting Conky service...${NC}"
    if [[ -f ~/.config/systemd/user/conky.service ]]; then
        if systemctl --user restart conky.service 2>/dev/null; then
            dmsg "Conky service restarted."
            log "Conky service restarted"
        else
            dmsg "Failed to restart Conky service."
            log "ERROR: Failed to restart conky.service"
            return 1
        fi
    else
        dmsg "Conky service not found. Please install Conky first."
        return 1
    fi
}

check_rkhunter() {
    echo -e "${BLUE}Running manual RKHunter scan...${NC}"
    local warn_log="/var/log/rkhunter_warnings.txt"
    
    # Run update and check
    if sudo /usr/local/bin/conky-rkhunter-wrapper.sh --update >/dev/null 2>&1 && \
       sudo /usr/local/bin/conky-rkhunter-wrapper.sh --propupd >/dev/null 2>&1; then
        
        local result_file
        result_file="$(mktemp)"
        
        if sudo /usr/local/bin/conky-rkhunter-wrapper.sh --check --sk > "$result_file" 2>/dev/null; then
            grep -iE "(warning|alert|suspect)" "$result_file" > "$warn_log" 2>/dev/null || true
            rm -f "$result_file"
            
            if [[ -s "$warn_log" ]]; then
                local count
                count="$(wc -l < "$warn_log")"
                dmsg "Scan complete: $count alert(s) found.\nView with option 12 or: cat $warn_log"
                log "RKHunter manual scan: $count warnings found"
            else
                dmsg "Scan complete: No alerts detected."
                log "RKHunter manual scan: Clean"
                rm -f "$warn_log"
            fi
        else
            dmsg "RKHunter check failed. Check logs for details."
            log "ERROR: RKHunter check command failed"
            return 1
        fi
    else
        dmsg "RKHunter update failed. Ensure you have internet connectivity."
        log "ERROR: RKHunter update failed"
        return 1
    fi
}

restore_system() {
    if ! dconfirm "Restore essential system packages? This will reinstall core desktop components."; then
        dmsg "System restoration canceled by user."
        return 1
    fi
    
    echo -e "${BLUE}Restoring essential system packages...${NC}"
    if [[ -z "$APT_HAS_UPDATED" ]]; then
        sudo apt update
        APT_HAS_UPDATED=1
    fi
    
    local -a essential_packages=(
        "ubuntu-desktop"
        "gdm3"
        "nautilus"
        "gvfs"
        "gvfs-backends"
        "network-manager"
    )
    
    local restored=0 skipped=0
    local -a packages_to_install=()
    
    for pkg in "${essential_packages[@]}"; do
        if dconfirm "Reinstall $pkg?"; then
            packages_to_install+=("$pkg")
        else
            ((skipped++)) || true
            log "Skipped package: $pkg"
        fi
    done

    if [[ ${#packages_to_install[@]} -gt 0 ]]; then
        if sudo apt install -y "${packages_to_install[@]}"; then
            for pkg in "${packages_to_install[@]}"; do
                ((restored++)) || true
                log "Restored package: $pkg"
            done
        else
            for pkg in "${packages_to_install[@]}"; do
                log "ERROR: Failed to restore $pkg"
            done
        fi
    fi
    
    # Fix broken dependencies if requested
    if dconfirm "Run 'sudo apt --fix-broken install -y' to fix dependency issues?"; then
        if sudo apt --fix-broken install -y; then
            log "Fixed broken dependencies"
        else
            log "WARNING: Could not fix all broken dependencies"
        fi
    fi
    
    dmsg "Restoration complete.\nRestored: $restored | Skipped: $skipped"
    log "System restoration batch complete"
}

########################################
# Main Menu (GUI with dialog)
########################################

main() {
    # Perform initial dependency check
    check_dependencies

    # Welcome banner
    dialog --clear --title "Conky Cybersecurity Monitor v2.1" --msgbox \
"This application installs, configures, and manages Conky with integrated security monitoring.

Features:
• Real-time system monitoring (CPU, RAM, Temp, Network)
• RKHunter rootkit detection with alerts
• Automated security scanning via systemd timers
• Desktop launcher & user-level services
• Pentesting tools installer (optional)
• Secure log management

Developed by jose-litium 2025
GitHub: https://github.com/jose-litium
LinkedIn: https://www.linkedin.com/in/josemmanueldiaz/" 20 75

    while true; do
        local choice
        choice=$(dialog --clear --backtitle "Conky Cybersecurity Monitor v2.1" \
            --title "Main Menu" \
            --menu "Select an action:" 30 75 20 \
            1 "Install Conky & Security Tools" \
            2 "Uninstall Conky Completely" \
            3 "Start Conky Monitor" \
            4 "Stop Conky Monitor" \
            5 "Restart Conky Monitor" \
            6 "Run Manual RKHunter Scan" \
            7 "Restore Essential System Packages" \
            8 "Install Auto RKHunter Service" \
            9 "Remove Auto RKHunter Service" \
            10 "Create Desktop Launcher" \
            11 "View Application Logs" \
            12 "View RKHunter Warnings" \
            13 "Delete Temporary Files" \
            14 "Clear Log File" \
            15 "Install Pentesting Tools" \
            16 "Clean System Logs (/var/log)" \
            17 "Exit Application" 2>&1 >/dev/tty) || continue

        case "$choice" in
            1) install_conky ;;
            2) uninstall_conky ;;
            3) start_conky ;;
            4) stop_conky ;;
            5) restart_conky ;;
            6) check_rkhunter ;;
            7) restore_system ;;
            8) install_rkhunter_service ;;
            9) remove_rkhunter_service ;;
            10) create_launcher ;;
            11) view_logs ;;
            12) view_rkhunter_warnings ;;
            13) delete_temporaries ;;
            14) clear_logs ;;
            15) install_pentest_tools ;;
            16) clean_var_log ;;
            17)
                dialog --clear --msgbox \
"Thank you for using Conky Cybersecurity Monitor!

For support or contributions:
GitHub: https://github.com/jose-litium
LinkedIn: https://www.linkedin.com/in/josemmanueldiaz

Stay secure! 🔒" 12 70
                clear
                exit 0
                ;;
            *) 
                dialog --clear --msgbox "Invalid option. Please select a number from the menu." 7 60 
                ;;
        esac
    done
}

########################################
# Script Entry Point
########################################

# Only execute if run directly (not sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    # Ensure we're running in a terminal with dialog support
    if [[ -z "$DISPLAY" && -z "$SSH_CONNECTION" ]]; then
        echo -e "${RED}Error: This script requires a graphical terminal or SSH with X11 forwarding.${NC}" >&2
        echo "Please run with: ssh -X user@host or in a GUI terminal" >&2
        exit 1
    fi
    
    # Check for dialog binary early
    if ! is_command_installed "dialog"; then
        echo -e "${RED}Error: 'dialog' is required but not installed.${NC}" >&2
        echo "Install with: sudo apt install dialog" >&2
        exit 1
    fi
    
    main "$@"
fi